// <auto-generated />
namespace BomAlunoNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reestruturalogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reestruturalogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201711142323407_reestruturalogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
